baseURL = "https://driver-pearl-81600.netlify.com/"

languageCode = "en-us"

title = "Martin Forslund"

theme = "ananke"
SectionPagesMenu = "main"
[params]
twitter = "https://twitter.com/t4ostra"
featured_image = "/image/Riddarholmen_from_Stockholm_City_Hall_tower.jpg"